[package]
name = "sudoku"
version = "0.1.0"
authors = ["Sebastian Ziebell <sebastian.ziebell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
clap = "2.33.3"
peg = "0.7.0"
